# Generated by Django 5.0.7 on 2024-07-25 06:10

import exel.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exel', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='reportsmodel',
            name='import_id',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='reportsmodel',
            name='file',
            field=models.FileField(upload_to='reports/', validators=[exel.models.validate_file_extension]),
        ),
    ]
